import type { Metadata } from "next";
import Image from "next/image";

import '@/CSS/normalize.css';
import '@/CSS/structure.css';
import '@/CSS/colors.css';

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Clémence Fortunato | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="bg">
          <Image src="/Sun.png" className="sun" width="1000" height="1000"alt=""></Image>
          <Image src="/wave2.svg" className="wave2" width="1920" height="1080" alt=""></Image>
          <Image src="/wave1.svg" className="wave1" width="1920" height="1080" alt=""></Image>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
